# Generated by Django 6.1 on 2026-09-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='logo',
            field=models.ImageField(blank=True, help_text="Shown on payslips for this unit's employees. PNG with transparency works best.", null=True, upload_to='unit-logos/'),
        ),
        migrations.AddField(
            model_name='historicalbusinessunit',
            name='logo',
            field=models.TextField(blank=True, help_text="Shown on payslips for this unit's employees. PNG with transparency works best.", max_length=100, null=True),
        ),
    ]
