# Generated by Django 6.1 on 2026-08-31 21:10

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NssfConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NSSF standard rates', max_length=120)),
                ('effective_from', models.DateField(unique=True)),
                ('employee_rate', models.DecimalField(decimal_places=4, default=Decimal('0.05'), max_digits=6)),
                ('employer_rate', models.DecimalField(decimal_places=4, default=Decimal('0.10'), max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('source_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'NSSF configuration',
                'verbose_name_plural': 'NSSF configurations',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalNssfConfig',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(default='NSSF standard rates', max_length=120)),
                ('effective_from', models.DateField(db_index=True)),
                ('employee_rate', models.DecimalField(decimal_places=4, default=Decimal('0.05'), max_digits=6)),
                ('employer_rate', models.DecimalField(decimal_places=4, default=Decimal('0.10'), max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('source_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical NSSF configuration',
                'verbose_name_plural': 'historical NSSF configurations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPayeTable',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('residency', models.CharField(choices=[('RESIDENT', 'Resident'), ('NON_RESIDENT', 'Non-resident')], default='RESIDENT', max_length=20)),
                ('effective_from', models.DateField()),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to keep a historical or draft table without using it.')),
                ('source_note', models.TextField(blank=True, help_text='Where these figures came from (e.g. URA PAYE rates page, date checked).')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical paye table',
                'verbose_name_plural': 'historical paye tables',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PayeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('residency', models.CharField(choices=[('RESIDENT', 'Resident'), ('NON_RESIDENT', 'Non-resident')], default='RESIDENT', max_length=20)),
                ('effective_from', models.DateField()),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to keep a historical or draft table without using it.')),
                ('source_note', models.TextField(blank=True, help_text='Where these figures came from (e.g. URA PAYE rates page, date checked).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-effective_from', 'residency'],
                'constraints': [models.UniqueConstraint(fields=('residency', 'effective_from'), name='uniq_paye_table_version')],
            },
        ),
        migrations.CreateModel(
            name='PayeBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('lower_bound', models.DecimalField(decimal_places=2, max_digits=14)),
                ('upper_bound', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for the top (open-ended) band.', max_digits=14, null=True)),
                ('marginal_rate', models.DecimalField(decimal_places=4, help_text='As a fraction, e.g. 0.30 for 30%.', max_digits=6)),
                ('cumulative_base', models.DecimalField(decimal_places=2, default=0, help_text='Tax accumulated on all income up to the lower bound of this band.', max_digits=14)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='statutory.payetable')),
            ],
            options={
                'ordering': ['table', 'sequence'],
            },
        ),
    ]
