# Generated by Django 6.1 on 2026-08-31 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrunline',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='payrunline',
            name='nssf_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='payrunline',
            name='tin',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
