# Generated by Django 6.1 on 2026-09-01 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('payroll', '0002_payrunline_email_payrunline_nssf_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrun',
            options={'ordering': ['-period_year', '-period_month', 'run_type', 'business_unit__name']},
        ),
        migrations.RemoveConstraint(
            model_name='payrun',
            name='uniq_run_per_period',
        ),
        migrations.AddField(
            model_name='historicalpayrun',
            name='business_unit',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Scope the run to one business unit. Leave blank for a group-wide run.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organization.businessunit'),
        ),
        migrations.AddField(
            model_name='payrun',
            name='business_unit',
            field=models.ForeignKey(blank=True, help_text='Scope the run to one business unit. Leave blank for a group-wide run.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pay_runs', to='organization.businessunit'),
        ),
        migrations.AddConstraint(
            model_name='payrun',
            constraint=models.UniqueConstraint(fields=('run_type', 'period_year', 'period_month', 'business_unit'), name='uniq_run_per_period_unit'),
        ),
        migrations.AddConstraint(
            model_name='payrun',
            constraint=models.UniqueConstraint(condition=models.Q(('business_unit__isnull', True)), fields=('run_type', 'period_year', 'period_month'), name='uniq_group_run_per_period'),
        ),
    ]
