# Generated by Django 6.1 on 2026-09-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_payrun_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeededuction',
            name='run_scope',
            field=models.CharField(choices=[('BOTH', 'Both runs'), ('SALARY', 'Salary run only'), ('EXPENSE', 'Expense Allowance run only')], default='BOTH', help_text='Which pay run this deduction is taken on (within what the code allows).', max_length=8, verbose_name='Apply on'),
        ),
        migrations.AddField(
            model_name='historicalemployeededuction',
            name='run_scope',
            field=models.CharField(choices=[('BOTH', 'Both runs'), ('SALARY', 'Salary run only'), ('EXPENSE', 'Expense Allowance run only')], default='BOTH', help_text='Which pay run this deduction is taken on (within what the code allows).', max_length=8, verbose_name='Apply on'),
        ),
    ]
