# Generated by Django 6.1 on 2026-09-15 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _approve_existing(apps, schema_editor):
    EmployeeDeduction = apps.get_model("payroll", "EmployeeDeduction")
    EmployeeDeduction.objects.update(approval_status="APPROVED")


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_employeededuction_run_scope_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeededuction',
            name='approval_note',
            field=models.CharField(blank=True, help_text='Shown to whoever attached the deduction — required when rejecting.', max_length=200, verbose_name='Reviewer note'),
        ),
        migrations.AddField(
            model_name='employeededuction',
            name='approval_reviewed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='employeededuction',
            name='approval_reviewed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_deductions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeededuction',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='employeededuction',
            name='number_of_runs',
            field=models.PositiveIntegerField(blank=True, help_text='Spread this deduction across exactly N pay runs (instalment-style, e.g. a loan repayment plan), then stop automatically. Leave blank for open-ended.', null=True, verbose_name='Number of runs'),
        ),
        migrations.AddField(
            model_name='employeededuction',
            name='runs_applied',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='How many runs this has been taken on so far. Maintained by the system at disbursement.'),
        ),
        migrations.AddField(
            model_name='historicalemployeededuction',
            name='approval_note',
            field=models.CharField(blank=True, help_text='Shown to whoever attached the deduction — required when rejecting.', max_length=200, verbose_name='Reviewer note'),
        ),
        migrations.AddField(
            model_name='historicalemployeededuction',
            name='approval_reviewed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployeededuction',
            name='approval_reviewed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalemployeededuction',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalemployeededuction',
            name='number_of_runs',
            field=models.PositiveIntegerField(blank=True, help_text='Spread this deduction across exactly N pay runs (instalment-style, e.g. a loan repayment plan), then stop automatically. Leave blank for open-ended.', null=True, verbose_name='Number of runs'),
        ),
        migrations.AddField(
            model_name='historicalemployeededuction',
            name='runs_applied',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='How many runs this has been taken on so far. Maintained by the system at disbursement.'),
        ),
        # Grandfather in every deduction that already existed before this approval
        # workflow shipped - only newly-attached deductions start life PENDING.
        migrations.RunPython(_approve_existing, migrations.RunPython.noop),
    ]
