# Generated by Django 6.1 on 2026-09-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_deduction_approval_and_runs'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrunline',
            name='bank_sort_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
