# Generated by Django 6.1 on 2026-08-31 21:10

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(help_text='Mandatory (Recommendation 6.11). Matching is always by ID, never by name.', max_length=20, unique=True, verbose_name='Staff ID')),
                ('full_legal_name', models.CharField(max_length=200)),
                ('national_id', models.CharField(blank=True, max_length=30, verbose_name='National ID')),
                ('position', models.CharField(help_text='Mandatory field (Recommendation 6.11).', max_length=150)),
                ('engagement_type', models.CharField(choices=[('PAYROLL_STAFF', 'Payroll staff'), ('CONTRACTOR', 'Independent contractor'), ('WAGE', 'Wage staff')], default='PAYROLL_STAFF', max_length=20)),
                ('monthly_gross_salary', models.DecimalField(decimal_places=2, default=0, help_text='Contractual monthly gross - the base for the month-end Salary run.', max_digits=14)),
                ('monthly_expense_allowance', models.DecimalField(decimal_places=2, default=0, help_text='Gross allowance - the base for the mid-month Expense Allowance run.', max_digits=14)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('bank_branch_code', models.CharField(blank=True, max_length=20)),
                ('bank_account_number', models.CharField(blank=True, max_length=30)),
                ('mobile_money_number', models.CharField(blank=True, max_length=20)),
                ('date_joined', models.DateField()),
                ('date_left', models.DateField(blank=True, help_text='Leaver date. A leaver is deactivated, never deleted.', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organization.businessunit')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organization.department')),
            ],
            options={
                'ordering': ['full_legal_name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEmployee',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('staff_id', models.CharField(db_index=True, help_text='Mandatory (Recommendation 6.11). Matching is always by ID, never by name.', max_length=20, verbose_name='Staff ID')),
                ('full_legal_name', models.CharField(max_length=200)),
                ('national_id', models.CharField(blank=True, max_length=30, verbose_name='National ID')),
                ('position', models.CharField(help_text='Mandatory field (Recommendation 6.11).', max_length=150)),
                ('engagement_type', models.CharField(choices=[('PAYROLL_STAFF', 'Payroll staff'), ('CONTRACTOR', 'Independent contractor'), ('WAGE', 'Wage staff')], default='PAYROLL_STAFF', max_length=20)),
                ('monthly_gross_salary', models.DecimalField(decimal_places=2, default=0, help_text='Contractual monthly gross - the base for the month-end Salary run.', max_digits=14)),
                ('monthly_expense_allowance', models.DecimalField(decimal_places=2, default=0, help_text='Gross allowance - the base for the mid-month Expense Allowance run.', max_digits=14)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('bank_branch_code', models.CharField(blank=True, max_length=20)),
                ('bank_account_number', models.CharField(blank=True, max_length=30)),
                ('mobile_money_number', models.CharField(blank=True, max_length=20)),
                ('date_joined', models.DateField()),
                ('date_left', models.DateField(blank=True, help_text='Leaver date. A leaver is deactivated, never deleted.', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('business_unit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organization.businessunit')),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organization.department')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical employee',
                'verbose_name_plural': 'historical employees',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
