# Generated by Django 6.1 on 2026-08-31 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, help_text='Used to email payslips.', max_length=254),
        ),
        migrations.AddField(
            model_name='employee',
            name='nssf_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='NSSF number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tin',
            field=models.CharField(blank=True, help_text='URA Tax Identification Number, for PAYE returns.', max_length=20, verbose_name='TIN'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='email',
            field=models.EmailField(blank=True, help_text='Used to email payslips.', max_length=254),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='nssf_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='NSSF number'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='tin',
            field=models.CharField(blank=True, help_text='URA Tax Identification Number, for PAYE returns.', max_length=20, verbose_name='TIN'),
        ),
    ]
